### ISSUE TITLE
Can't access the logs

### ISSUE THREAD

**Issue by bartverbruggen** [kayalion/shiza#1]
When trying to access the logs in shiza for a specific env, I get the following error:

```
:'-(
Whoopsie!

An exception is thrown and it was not caught by the system.

ride\library\system\exception\SystemException: Could not execute /home/kayalion/Projects/Shiza/web-admin/src/logresolvemerge.pl /tmp/temptPAJRM /tmp/tempThoaJb: command not found

The code:

/home/b/bruser/www/be.bruusk.root/vendor/ride/lib-system/src/ride/library/system/System.php:170

164: 
165:         $output = array();
166: 
167:         exec($command, $output, $code);
168: 
169:         if ($code == 127) {
170:             throw new SystemException('Could not execute ' . $command . ': command not found');
171:         }
172: 
173:         return $output;
The trace:

#0 /home/b/bruser/www/be.bruusk.root/vendor/ride/app/src/ride/application/system/System.php(464): ride\library\system\System->executeCommand('/home/kayalion/...', 127)
#1 /home/b/bruser/www/be.bruusk.root/vendor/ride/lib-system/src/ride/library/system/System.php(123): ride\application\system\System->executeCommand('/home/kayalion/...', 127)
#2 /home/b/bruser/www/be.bruusk.root/vendor/kayalion/shiza/src/shiza/manager/web/ApacheSshWebManager.php(104): ride\library\system\System->execute('/home/kayalion/...', 127)
#3 /home/b/bruser/www/be.bruusk.root/vendor/kayalion/shiza/src/shiza/controller/ProjectEnvironmentController.php(194): shiza\manager\web\ApacheSshWebManager->getLog(Object(ride\application\orm\entry\proxy\ProjectEnvironmentEntryProxy))
#4 [internal function]: shiza\controller\ProjectEnvironmentController->logAction(Object(ride\application\orm\OrmManager), Object(shiza\service\ServerService), Object(ride\application\orm\entry\proxy\ProjectEntryProxy), Object(ride\application\orm\entry\proxy\ProjectEnvironmentEntryProxy))
#5 /home/b/bruser/www/be.bruusk.root/vendor/ride/lib-reflection/src/ride/library/reflection/Callback.php(161): call_user_func_array(Array, Array)
#6 /home/b/bruser/www/be.bruusk.root/vendor/ride/lib-dependency/src/ride/library/dependency/DependencyInjector.php(631): ride\library\reflection\Callback->invokeWithArguments(Array)
#7 /home/b/bruser/www/be.bruusk.root/vendor/ride/lib-dependency/src/ride/library/dependency/DependencyInjector.php(600): ride\library\dependency\DependencyInjector->invokeCallback(Object(ride\library\reflection\Callback), Array, NULL, false)
#8 /home/b/bruser/www/be.bruusk.root/vendor/ride/web/src/ride/web/mvc/dispatcher/LoggedDispatcher.php(97): ride\library\dependency\DependencyInjector->invoke(Object(ride\library\reflection\Callback), Array, false)
#9 /home/b/bruser/www/be.bruusk.root/vendor/ride/lib-mvc/src/ride/library/mvc/dispatcher/GenericDispatcher.php(77): ride\web\mvc\dispatcher\LoggedDispatcher->invokeCallback()
#10 /home/b/bruser/www/be.bruusk.root/vendor/ride/web/src/ride/web/WebApplication.php(526): ride\library\mvc\dispatcher\GenericDispatcher->dispatch(Object(ride\web\mvc\Request), Object(ride\library\mvc\Response))
#11 /home/b/bruser/www/be.bruusk.root/vendor/ride/web/src/ride/web/WebApplication.php(411): ride\web\WebApplication->dispatch()
#12 /home/b/bruser/www/be.bruusk.root/vendor/ride/app/src/ride/application/system/System.php(442): ride\web\WebApplication->service()
#13 /home/b/bruser/www/be.bruusk.root/public/index.php(12): ride\application\system\System->service('web')
#14 {main}
```

**Comment by kayalion** [comment]
Fixed through [ff1fa1a](https://github.com/kayalion/shiza/commit/ff1fa1a2fcf119dd7c0792ea1802f45880cb1c36)
